# F1 Lap Time Prediction - Data Download and Inspection

This project aims to predict a Formula 1 driver's next lap time using information available at the end of the current lap. I will explore previous lap times, tyre conditions and weather to prepare the data for a machine learning regression model.

In this notebook, I use the FastF1 Python library to download and inspect race data, starting with Monza 2024. This helps me understand the available data before moving on to exploratory analysis.

## Imports

In [17]:
import fastf1

## Event selection

In [18]:
schedule=fastf1.get_event_schedule(2024, include_testing=False)
schedule[["RoundNumber", "EventName", "EventDate"]]

    RoundNumber                  EventName  EventDate
1             1         Bahrain Grand Prix 2024-03-02
2             2   Saudi Arabian Grand Prix 2024-03-09
3             3      Australian Grand Prix 2024-03-24
4             4        Japanese Grand Prix 2024-04-07
5             5         Chinese Grand Prix 2024-04-21
6             6           Miami Grand Prix 2024-05-05
7             7  Emilia Romagna Grand Prix 2024-05-19
8             8          Monaco Grand Prix 2024-05-26
9             9        Canadian Grand Prix 2024-06-09
10           10         Spanish Grand Prix 2024-06-23
11           11        Austrian Grand Prix 2024-06-30
12           12         British Grand Prix 2024-07-07
13           13       Hungarian Grand Prix 2024-07-21
14           14         Belgian Grand Prix 2024-07-28
15           15           Dutch Grand Prix 2024-08-25
16           16         Italian Grand Prix 2024-09-01
17           17      Azerbaijan Grand Prix 2024-09-15
18           18       Singapore Grand Prix 2024-09-22
19           19   United States Grand Prix 2024-10-20
20           20     Mexico City Grand Prix 2024-10-27
21           21       São Paulo Grand Prix 2024-11-03
22           22       Las Vegas Grand Prix 2024-11-23
23           23           Qatar Grand Prix 2024-12-01
24           24       Abu Dhabi Grand Prix 2024-12-08

## Race Selection

In [19]:
session=fastf1.get_session(2024, "Monza", "R")
session.event[["EventName", "EventDate"]]

EventName     Italian Grand Prix
EventDate    2024-09-01 00:00:00
dtype: object

## Session Load

In [20]:
session.load(telemetry=False)
laps=session.laps
laps.head()

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:18.931000,LEC,16,0 days 00:01:28.179000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.989000,...,True,Ferrari,0 days 00:55:50.494000,NaT,1,2.0,False,,False,False
1,0 days 00:58:44.327000,LEC,16,0 days 00:01:25.396000,2.0,1.0,NaT,NaT,0 days 00:00:27.707000,0 days 00:00:29.265000,...,True,Ferrari,0 days 00:57:18.931000,NaT,1,2.0,False,,False,True
2,0 days 01:00:09.506000,LEC,16,0 days 00:01:25.179000,3.0,1.0,NaT,NaT,0 days 00:00:27.679000,0 days 00:00:29.001000,...,True,Ferrari,0 days 00:58:44.327000,NaT,1,2.0,False,,False,True
3,0 days 01:01:34.316000,LEC,16,0 days 00:01:24.810000,4.0,1.0,NaT,NaT,0 days 00:00:27.653000,0 days 00:00:28.883000,...,True,Ferrari,0 days 01:00:09.506000,NaT,1,2.0,False,,False,True
4,0 days 01:02:58.919000,LEC,16,0 days 00:01:24.603000,5.0,1.0,NaT,NaT,0 days 00:00:27.630000,0 days 00:00:28.790000,...,True,Ferrari,0 days 01:01:34.316000,NaT,1,2.0,False,,False,True

## View lap data in a separate tab

In [21]:
import pandas as pd

laps_view = pd.DataFrame(laps).copy()
laps_view.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:18.931000,LEC,16,0 days 00:01:28.179000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.989000,...,True,Ferrari,0 days 00:55:50.494000,NaT,1,2.0,False,,False,False
1,0 days 00:58:44.327000,LEC,16,0 days 00:01:25.396000,2.0,1.0,NaT,NaT,0 days 00:00:27.707000,0 days 00:00:29.265000,...,True,Ferrari,0 days 00:57:18.931000,NaT,1,2.0,False,,False,True
2,0 days 01:00:09.506000,LEC,16,0 days 00:01:25.179000,3.0,1.0,NaT,NaT,0 days 00:00:27.679000,0 days 00:00:29.001000,...,True,Ferrari,0 days 00:58:44.327000,NaT,1,2.0,False,,False,True
3,0 days 01:01:34.316000,LEC,16,0 days 00:01:24.810000,4.0,1.0,NaT,NaT,0 days 00:00:27.653000,0 days 00:00:28.883000,...,True,Ferrari,0 days 01:00:09.506000,NaT,1,2.0,False,,False,True
4,0 days 01:02:58.919000,LEC,16,0 days 00:01:24.603000,5.0,1.0,NaT,NaT,0 days 00:00:27.630000,0 days 00:00:28.790000,...,True,Ferrari,0 days 01:01:34.316000,NaT,1,2.0,False,,False,True

## Analysing data

In [22]:
laps.describe()

,Time,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,LapStartTime,LapStartDate,Position
count,1008,1008,1008.000000,1008.000000,30,31,988,1008,1008,985,1008,1008,1008.000000,1008.000000,977.000000,1008.000000,1008.000000,1008,0,1008.000000
mean,0 days 01:34:15.317083333,0 days 00:01:25.789875992,26.685516,1.856151,0 days 01:30:36.192600,0 days 01:29:24.016709677,0 days 00:00:28.292245951,0 days 00:00:29.083601190,0 days 00:00:28.354501984,0 days 01:34:00.508487309,0 days 01:33:46.987893849,0 days 01:34:15.342750,314.420635,319.096230,312.377687,322.920635,12.872024,0 days 01:32:49.522088293,NaT,10.030754
min,0 days 00:57:18.375000,0 days 00:01:21.432000,1.000000,1.000000,0 days 01:03:53.551000,0 days 01:03:14.706000,0 days 00:00:26.877000,0 days 00:00:27.439000,0 days 00:00:26.804000,0 days 00:57:46.160000,0 days 00:56:50.171000,0 days 00:57:18.645000,225.000000,213.000000,294.000000,247.000000,1.000000,0 days 00:55:50.494000,NaT,1.000000
25%,0 days 01:15:08.673750,0 days 00:01:23.853500,13.000000,1.000000,0 days 01:17:34.850250,0 days 01:16:36.683000,0 days 00:00:27.441750,0 days 00:00:28.622750,0 days 00:00:27.784500,0 days 01:15:17.603000,0 days 01:14:40.024750,0 days 01:15:08.702000,312.000000,315.000000,311.000000,319.000000,6.000000,0 days 01:13:42.878250,NaT,5.000000
50%,0 days 01:34:24.777000,0 days 00:01:24.980500,27.000000,2.000000,0 days 01:25:45.254000,0 days 01:23:23.821000,0 days 00:00:27.617000,0 days 00:00:29.023500,0 days 00:00:28.234000,0 days 01:34:03.154000,0 days 01:33:57.051500,0 days 01:34:24.799500,314.000000,317.000000,312.000000,323.000000,11.000000,0 days 01:33:01.258500,NaT,10.000000
75%,0 days 01:53:17.670000,0 days 00:01:25.971500,40.000000,2.000000,0 days 01:43:57.715000,0 days 01:43:24.501000,0 days 00:00:27.787500,0 days 00:00:29.423250,0 days 00:00:28.589500,0 days 01:52:34.860000,0 days 01:52:50.255250,0 days 01:53:17.679750,317.000000,322.000000,314.000000,328.000000,18.000000,0 days 01:51:54.657250,NaT,15.000000
max,0 days 02:11:52.787000,0 days 00:02:00.178000,53.000000,4.000000,0 days 02:08:23.328000,0 days 02:07:58.096000,0 days 00:01:01.963000,0 days 00:00:32.786000,0 days 00:00:41.216000,0 days 02:10:56.547000,0 days 02:11:25.107000,0 days 02:11:52.805000,340.000000,343.000000,324.000000,357.000000,43.000000,0 days 02:10:29.059000,NaT,20.000000
std,0 days 00:21:50.079105288,0 days 00:00:04.224563222,15.283267,0.696239,0 days 00:16:22.658147932,0 days 00:16:40.609707024,0 days 00:00:03.800323836,0 days 00:00:00.696614008,0 days 00:00:01.055276079,0 days 00:21:22.590665472,0 days 00:21:50.452528378,0 days 00:21:50.074101468,6.101073,8.244866,2.605093,12.828858,8.895425,0 days 00:21:51.198720965,NaN,5.515893

In [23]:
laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1008 non-null   timedelta64[ns]
 1   Driver              1008 non-null   object
 2   DriverNumber        1008 non-null   object
 3   LapTime             1008 non-null   timedelta64[ns]
 4   LapNumber           1008 non-null   float64
 5   Stint               1008 non-null   float64
 6   PitOutTime          30 non-null     timedelta64[ns]
 7   PitInTime           31 non-null     timedelta64[ns]
 8   Sector1Time         988 non-null    timedelta64[ns]
 9   Sector2Time         1008 non-null   timedelta64[ns]
 10  Sector3Time         1008 non-null   timedelta64[ns]
 11  Sector1SessionTime  985 non-null    timedelta64[ns]
 12  Sector2SessionTime  1008 non-null   timedelta64[ns]
 13  Sector3SessionTime  1008 non-null   timedelta64[ns]
 14  SpeedI1             1008 non-null   float64
 15  SpeedI2             1008 non-null   float64
 16  SpeedFL             977 non-null    float64
 17  SpeedST             1008 non-null   float64
 18  IsPersonalBest      1008 non-null   bool
 19  Compound            1008 non-null   object
 20  TyreLife            1008 non-null   float64
 21  FreshTyre           1008 non-null   bool
 22  Team                1008 non-null   object
 23  LapStartTime        1008 non-null   timedelta64[ns]
 24  LapStartDate        0 non-null      datetime64[ns]
 25  TrackStatus         1008 non-null   object
 26  Position            1008 non-null   float64
 27  Deleted             1008 non-null   bool
 28  DeletedReason       1008 non-null   object
 29  FastF1Generated     1008 non-null   bool
 30  IsAccurate          1008 non-null   bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 209.8+ KB

In [24]:
laps.isnull().sum().sort_values(ascending=False)

LapStartDate          1008
PitOutTime             978
PitInTime              977
SpeedFL                 31
Sector1SessionTime      23
Sector1Time             20
DriverNumber             0
Stint                    0
LapNumber                0
LapTime                  0
Sector2Time              0
Sector3Time              0
Sector2SessionTime       0
Driver                   0
Time                     0
SpeedI1                  0
Sector3SessionTime       0
SpeedST                  0
SpeedI2                  0
Compound                 0
TyreLife                 0
FreshTyre                0
IsPersonalBest           0
Team                     0
LapStartTime             0
TrackStatus              0
Position                 0
Deleted                  0
DeletedReason            0
FastF1Generated          0
IsAccurate               0
dtype: int64

## Missing first sector values

In [25]:
laps.loc[
    laps["Sector1Time"].isna(),
    ["Driver", "LapNumber", "Sector1Time"]
]

     Driver  LapNumber Sector1Time
0       LEC        1.0         NaT
53      PIA        1.0         NaT
106     NOR        1.0         NaT
159     SAI        1.0         NaT
212     HAM        1.0         NaT
265     VER        1.0         NaT
318     RUS        1.0         NaT
371     PER        1.0         NaT
424     ALB        1.0         NaT
477     MAG        1.0         NaT
530     ALO        1.0         NaT
583     COL        1.0         NaT
636     RIC        1.0         NaT
689     OCO        1.0         NaT
741     GAS        1.0         NaT
793     BOT        1.0         NaT
845     HUL        1.0         NaT
897     ZHO        1.0         NaT
949     STR        1.0         NaT
1001    TSU        1.0         NaT

Sector1Time is missing on lap 1. I still don't know the cause, but I will be looking into it now and then decide whether or not it is useful to have first lap data for the model still.

## Checking SpeedFL Missing Values

In [26]:
laps.loc[
    laps["SpeedFL"].isna(),
    ["Driver", "LapNumber", "SpeedFL", "PitInTime", "PitOutTime"]
]

     Driver  LapNumber  SpeedFL              PitInTime PitOutTime
14      LEC       15.0      NaN 0 days 01:17:08.772000        NaT
68      PIA       16.0      NaN 0 days 01:18:30.160000        NaT
90      PIA       38.0      NaN 0 days 01:49:32.401000        NaT
119     NOR       14.0      NaN 0 days 01:15:43.308000        NaT
137     NOR       32.0      NaN 0 days 01:41:15.813000        NaT
177     SAI       19.0      NaN 0 days 01:22:54.237000        NaT
226     HAM       15.0      NaN 0 days 01:17:15.039000        NaT
248     HAM       37.0      NaN 0 days 01:48:27.801000        NaT
286     VER       22.0      NaN 0 days 01:27:13.547000        NaT
305     VER       41.0      NaN 0 days 01:54:11.181000        NaT
328     RUS       11.0      NaN 0 days 01:11:38.608000        NaT
350     RUS       33.0      NaN 0 days 01:43:07.940000        NaT
393     PER       23.0      NaN 0 days 01:28:42.654000        NaT
405     PER       35.0      NaN 0 days 01:45:54.606000        NaT
440     ALB       17.0      NaN 0 days 01:20:21.362000        NaT
490     MAG       14.0      NaN 0 days 01:16:04.594000        NaT
541     ALO       12.0      NaN 0 days 01:13:10.512000        NaT
564     ALO       35.0      NaN 0 days 01:46:11.502000        NaT
598     COL       16.0      NaN 0 days 01:19:07.220000        NaT
646     RIC       11.0      NaN 0 days 01:11:48.208000        NaT
719     OCO       31.0      NaN 0 days 01:40:36.781000        NaT
750     GAS       10.0      NaN 0 days 01:10:24.834000        NaT
770     GAS       30.0      NaN 0 days 01:39:22.472000        NaT
825     BOT       33.0      NaN 0 days 01:43:41.062000        NaT
849     HUL        5.0      NaN 0 days 01:03:14.706000        NaT
876     HUL       32.0      NaN 0 days 01:42:22.031000        NaT
911     ZHO       15.0      NaN 0 days 01:17:44.783000        NaT
967     STR       19.0      NaN 0 days 01:23:23.821000        NaT
984     STR       36.0      NaN 0 days 01:47:52.793000        NaT
998     STR       50.0      NaN 0 days 02:07:58.096000        NaT
1007    TSU        7.0      NaN 0 days 01:06:23.674000        NaT

All missing SpeedFL values coincide with pit entries.

## Weather Data

In [27]:
weather=session.weather_data
weather.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:26.141000,33.2,38.0,993.8,False,52.1,318,0.7
1,0 days 00:01:26.139000,33.2,37.0,993.9,False,52.1,207,1.0
2,0 days 00:02:26.141000,33.2,37.0,993.9,False,52.8,230,1.3
3,0 days 00:03:26.146000,33.2,36.0,993.8,False,52.8,200,0.7
4,0 days 00:04:26.151000,33.3,36.0,993.8,False,52.8,182,0.8

In [28]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           133 non-null    timedelta64[ns]
 1   AirTemp        133 non-null    float64
 2   Humidity       133 non-null    float64
 3   Pressure       133 non-null    float64
 4   Rainfall       133 non-null    bool
 5   TrackTemp      133 non-null    float64
 6   WindDirection  133 non-null    int64
 7   WindSpeed      133 non-null    float64
dtypes: bool(1), float64(5), int64(1), timedelta64[ns](1)
memory usage: 7.5 KB

## Data that will be used

In [29]:
seasons=range(2022,2026)
schedules=[]

for year in seasons:
    schedule=fastf1.get_event_schedule(year, include_testing=False)
    schedule["Season"]=year
    schedules.append(schedule)

events=pd.concat(schedules,ignore_index=True)
events.groupby("Season")["RoundNumber"].count()

C:\Users\Francisco\AppData\Local\Temp\ipykernel_37284\1510962178.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule["Season"]=year
C:\Users\Francisco\AppData\Local\Temp\ipykernel_37284\1510962178.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule["Season"]=year
C:\Users\Francisco\AppData\Local\Temp\ipykernel_37284\1510962178.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule["Season"]=year
C:\Users\Francisco\AppData\Local\Temp\ipykernel_37284\1510962178.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule["Season"]=year

Season
2022    22
2023    22
2024    24
2025    24
Name: RoundNumber, dtype: int64

## Saving Data

In [30]:
from pathlib import Path

project_root=Path.cwd()
if project_root.name=="notebooks":
    project_root=project_root.parent

data_dir=project_root / "data"
data_dir.mkdir(exist_ok=True)
events.to_csv(data_dir / "events_2022_2025.csv", index=False)